import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jdewi
 */
public class CoinFlipGui extends javax.swing.JFrame {

    String[] coinArray = {"---", " \\ ", " | ", " / "};
    
    public int placeInArray = 0;
    public int numberOfFlips = 4;
    public int timerLoop = 0;
    public int movingInterval = 4;
    public int originalX = 0;
    public int originalY = 0;
    public Boolean coinFlipping = false;
    public Boolean onHeads = false;
    public Boolean backPressed = false;
    
    public Boolean getBackPressed() {
        return this.backPressed;
    }
    
    public void setBackPressed(Boolean status) {
        this.backPressed = status;
    }
    
    /**
     * Creates new form CoinFlipGui
     */
    public CoinFlipGui() {
        initComponents();
        
        jLabel4.setText("");
        
        originalX = jPanel3.getLocation().x;
        originalY = jPanel3.getLocation().y;
        
        //jPanel3.setLayout(null);
        //jPanel3.setLocation(originalX, originalY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(537, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Press the button to spin the coin");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(161, 16));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 356, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("The Result:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 103, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Spin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(58, 199, 144, 65);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setText("Heads");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 120, 90, 37);

        jButton2.setText("Back to Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 280, 170, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("---");
        jLabel2.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(326, 164, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!coinFlipping){
            coinFlipping = true;
            jLabel4.setText("");
            
            StartCoinFlip();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!coinFlipping) {
            backPressed = true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoinFlipGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoinFlipGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoinFlipGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoinFlipGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoinFlipGui().setVisible(true);
            }
        });
    }
    
    public void StartCoinFlip() {
        onHeads = Results();
        
        TimerTask spinCoin = new TimerTask() {
            @Override
            public void run() {
                
                if (timerLoop == 0) {
                    if (numberOfFlips <= 0){

                        numberOfFlips = 4;
                        placeInArray = 0;
                        jLabel2.setText(coinArray[placeInArray]);
                        coinFlipping = false;
                        
                        if (onHeads) {
                            jLabel4.setText("Heads");
                        } else {
                            jLabel4.setText("Tails");
                        }
                        
                        cancel();

                    } else {

                        AdvanceCoin();

                    }
                    
                    timerLoop = 4;
                    
                } else {
                    timerLoop--;
                }
                
                MoveCoin();
                
            }
            
        };
        
        Timer timer = new Timer();
        timer.schedule(spinCoin, 0, 50);
    }
    
    
    public void AdvanceCoin() {
        jLabel2.setText(coinArray[placeInArray]);
        if (placeInArray == coinArray.length - 1){
            placeInArray = 0;
            
            if (numberOfFlips > 0) {
                numberOfFlips--;
            }
        } else {
            placeInArray++;
        }
    }
    
    public void MoveCoin(){
        
        if (numberOfFlips >= 3){
            jPanel3.setLocation(jPanel3.getLocation().x, jPanel3.getLocation().y - movingInterval);
        } else {
            if (!((jPanel3.getLocation().y + movingInterval) > originalY)) {
                jPanel3.setLocation(jPanel3.getLocation().x, jPanel3.getLocation().y + movingInterval);
            } else {
                jPanel3.setLocation(jPanel3.getLocation().x, originalY);
            }
        }
    }
    
    public Boolean Results() {
        
        int numberResult = (int) (Math.random() * 2);;
        
        if (numberResult == 0) {
            return false;
        } else {
            return true;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
